following_follow:
    path:     /follow
    defaults: { _controller: AppBundle:Following:follow }
    methods: POST

following_unfollow:
    path:     /unfollow
    defaults: { _controller: AppBundle:Following:unfollow }
    methods: POST

following_following:
    path:     /following/{nick}
    defaults: { _controller: AppBundle:Following:following, nick: null }
    methods: GET

following_followings:
    path:     /followings/{nick}
    defaults: { _controller: AppBundle:Following:followings, nick: null }
    methods: GET

following_followed:
    path:     /followed/{nick}
    defaults: { _controller: AppBundle:Following:followed, nick: null }
    methods: GET

following_verify_follow:
    path:     /verify-follow
    defaults: { _controller: AppBundle:Following:verifyFollow }
    methods: POST
