like_publication:
    path: /like/{id}
    defaults: { _controller: "AppBundle:Like:like", id: null }
    methods: POST

unlike_publication:
    path: /unlike/{id}
    defaults: { _controller: "AppBundle:Like:unlike", id: null }
    methods: POST

likes_publication:
    path: /likes/{nick}
    defaults: { _controller: "AppBundle:Like:likes", nick: null }
    methods: GET

mylikes_publication:
    path: /likes-publications/{nick}
    defaults: { _controller: "AppBundle:Like:likePublications", nick: null }
    methods: GET
