create_publication:
    path:     create
    defaults: { _controller: AppBundle:Publication:create }
    methods: POST

list_publication:
    path:     list
    defaults: { _controller: AppBundle:Publication:list }
    methods: POST
