let url = 'http://localhost:8000/';

export var GLOBAL = {
	url_register: url+'register',
	url_update: url+'configuration',
	url_upload_avatar: url+'upload-image-user',
	url_avatar: url+'uploads/users',
	url_search: url+'search',
	url_users: url+'people',
  url_login: url+'login',
	url_nick: url+'nick-test',
	url_follow: url+'follow',
	url_unfollow: url+'unfollow',
	url_following: url+'following/',
	url_create: url+'create',
	url_list: url+'list',
	url_delete: url+'delete/',
	url_like: url+'like/',
	url_unlike: url+'unlike/',
	url_document: url+'uploads/publications/documents/',
	url_image: url+'uploads/publications/images/',
	url_likes: url+'likes/',
	url_publications: url+'publications',
	url_likes_publications: url+'likes-publications/',
	url_profile: url+'profile/',
	url_followings: url+'followings/',
	url_followed: url+'followed/',
	url_number_notifications: url+'notifications/get',
	url_notifications: url+'notifications',
	url_message: url+'private-message',
	url_sended: url+'sended',
	url_received: url+'received',
	url_notreaded: url+'notreaded',
	ip: '127.0.0.1',
};
